name: CI / CD

on: [push]

jobs:
  app-build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11 for app
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install app dependencies with Pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
        working-directory: ./app

      - name: Run app tests with Pipenv
        run: pipenv run pytest
        working-directory: ./app